"""add_career_profile

Revision ID: 4d92e0484a6d
Revises: f8bb71f58562
Create Date: 2026-04-24 19:46:16.466209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4d92e0484a6d'
down_revision: Union[str, None] = 'f8bb71f58562'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('career_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('salary_range', sa.String(length=50), nullable=True),
    sa.Column('job_growth_percentage', sa.String(length=50), nullable=True),
    sa.Column('time_to_start', sa.String(length=50), nullable=True),
    sa.Column('experience_level', sa.String(length=50), nullable=True),
    sa.Column('advantages', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('challenges', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('required_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_profiles_id'), 'career_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_career_profiles_slug'), 'career_profiles', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_career_profiles_slug'), table_name='career_profiles')
    op.drop_index(op.f('ix_career_profiles_id'), table_name='career_profiles')
    op.drop_table('career_profiles')
    # ### end Alembic commands ###
