"""add_execution_os_fields

Revision ID: 6aa97e679a48
Revises: 4d92e0484a6d
Create Date: 2026-04-24 20:11:42.098092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6aa97e679a48'
down_revision: Union[str, None] = '4d92e0484a6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('estimated_minutes', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('due_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('task_type', sa.String(length=50), nullable=True))
    op.add_column('tasks', sa.Column('energy_level', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'energy_level')
    op.drop_column('tasks', 'task_type')
    op.drop_column('tasks', 'due_date')
    op.drop_column('tasks', 'estimated_minutes')
    # ### end Alembic commands ###
