"""adaptive_roadmap_system

Revision ID: d92f3571e6bf
Revises: 6aa97e679a48
Create Date: 2026-05-03 22:41:33.452385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd92f3571e6bf'
down_revision: Union[str, None] = '6aa97e679a48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_progress',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('total_xp', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('level_title', sa.String(length=100), nullable=True),
    sa.Column('current_streak', sa.Integer(), nullable=True),
    sa.Column('longest_streak', sa.Integer(), nullable=True),
    sa.Column('last_activity_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('badges', sa.Text(), nullable=True),
    sa.Column('tasks_completed', sa.Integer(), nullable=True),
    sa.Column('projects_completed', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_progress_user_id'), 'user_progress', ['user_id'], unique=True)
    op.create_table('task_feedbacks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('feedback', sa.String(length=20), nullable=False),
    sa.Column('time_taken_minutes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_feedbacks_task_id'), 'task_feedbacks', ['task_id'], unique=False)
    op.create_index(op.f('ix_task_feedbacks_user_id'), 'task_feedbacks', ['user_id'], unique=False)
    op.add_column('roadmap_nodes', sa.Column('phase_number', sa.Integer(), nullable=True))
    op.add_column('roadmap_nodes', sa.Column('xp_reward', sa.Integer(), nullable=True))
    op.add_column('roadmap_nodes', sa.Column('is_locked', sa.Boolean(), nullable=True))
    op.add_column('roadmap_nodes', sa.Column('unlock_xp_required', sa.Integer(), nullable=True))
    op.alter_column('roadmap_nodes', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.add_column('tasks', sa.Column('order_index', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('action_steps', sa.Text(), nullable=True))
    op.add_column('tasks', sa.Column('expected_outcome', sa.Text(), nullable=True))
    op.add_column('tasks', sa.Column('validation_type', sa.String(length=50), nullable=True))
    op.add_column('tasks', sa.Column('validation_criteria', sa.Text(), nullable=True))
    op.add_column('tasks', sa.Column('resources', sa.Text(), nullable=True))
    op.add_column('tasks', sa.Column('skill_tags', sa.Text(), nullable=True))
    op.add_column('tasks', sa.Column('xp_reward', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('project_linked', sa.Boolean(), nullable=True))
    op.add_column('tasks', sa.Column('last_feedback', sa.String(length=20), nullable=True))
    op.add_column('tasks', sa.Column('skip_count', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('is_accelerated', sa.Boolean(), nullable=True))
    op.add_column('tasks', sa.Column('is_injected', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'is_injected')
    op.drop_column('tasks', 'is_accelerated')
    op.drop_column('tasks', 'skip_count')
    op.drop_column('tasks', 'last_feedback')
    op.drop_column('tasks', 'project_linked')
    op.drop_column('tasks', 'xp_reward')
    op.drop_column('tasks', 'skill_tags')
    op.drop_column('tasks', 'resources')
    op.drop_column('tasks', 'validation_criteria')
    op.drop_column('tasks', 'validation_type')
    op.drop_column('tasks', 'expected_outcome')
    op.drop_column('tasks', 'action_steps')
    op.drop_column('tasks', 'order_index')
    op.alter_column('roadmap_nodes', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('roadmap_nodes', 'unlock_xp_required')
    op.drop_column('roadmap_nodes', 'is_locked')
    op.drop_column('roadmap_nodes', 'xp_reward')
    op.drop_column('roadmap_nodes', 'phase_number')
    op.drop_index(op.f('ix_task_feedbacks_user_id'), table_name='task_feedbacks')
    op.drop_index(op.f('ix_task_feedbacks_task_id'), table_name='task_feedbacks')
    op.drop_table('task_feedbacks')
    op.drop_index(op.f('ix_user_progress_user_id'), table_name='user_progress')
    op.drop_table('user_progress')
    # ### end Alembic commands ###
